### PR TITLE
Bump Rustler to 0.34.0 in Cargo.toml (not 0.35.0), IOW, downgrade in mix.exs

### LINKED ISSUE #68: bump rustler to 0.35.0 failed
We have been slacking a lot on updating our dependent library packages/libraries, so I have been working on this with the help of dependabot. Also, I have added cargo packages as the target to be updated automatically by dependabot (see #62). This will also work fine for proper correspondence between mix and cargo.

As a result, #67 tries to bump rustler in Cargo.toml significantly, from 0.32.1 to 0.35.0. 
This has led to the discovery of issues whereby existing sources cannot be built. We need to look step by step to see what the cause is.

Related info:
https://hexdocs.pm/rustler/upgrade.html#content

### PR DESCRIPTION
**Pull request by takasehideki**
~~This PR is trying to bump Rustler in Cargo.toml to 0.35.0. Also see #68 
Note that this is now working in progress, since we are trying to bump it step by step by referring [upgrade guide of Rustler](https://hexdocs.pm/rustler/upgrade.html).~~

--- 

As a result, we decided to bump Rustler in Cargo.toml to 0.34.0, not 0.35.0, in this PR.
The bump to 0.35.0, the current latest version, will be made after Zenoh's update to v1.0.0 first (#59), and then continued in #68.

### CODE REVIEW

**Comment by takasehideki** [comment]
I have confirmed that bump to 0.34.0 works fine. However, some warnings have occurred. 
I think these should be eliminated.

```
   Compiling zenohex_nif v0.3.0 (/home/takase/zenoh/zenohex/native/zenohex_nif)
warning: use of deprecated constant `rustler_init::explicit_nif_functions`: Passing NIF functions explicitly is deprecated and this argument is ignored, please remove it
  --> src/lib.rs:59:5
   |
59 | /     [
60 | |         zenoh_open,
61 | |         session::declare_publisher,
62 | |         session::declare_subscriber,
...  |
83 | |         keyexpr::key_expr_intersects,
84 | |     ],
   | |_____^
   |
   = note: `#[warn(deprecated)]` on by default

warning: unused return value of `Result::<T, E>::is_ok` that must be used
  --> src/lib.rs:46:5
   |
46 |     rustler::resource!(SessionRef, env);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: if you intended to assert that this is ok, consider `.unwrap()` instead
   = note: `#[warn(unused_must_use)]` on by default
   = note: this warning originates in the macro `rustler::resource` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unused return value of `Result::<T, E>::is_ok` that must be used
  --> src/lib.rs:47:5
   |
47 |     rustler::resource!(PublisherRef, env);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: if you intended to assert that this is ok, consider `.unwrap()` instead
   = note: this warning originates in the macro `rustler::resource` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unused return value of `Result::<T, E>::is_ok` that must be used
  --> src/lib.rs:48:5
   |
48 |     rustler::resource!(SubscriberRef, env);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: if you intended to assert that this is ok, consider `.unwrap()` instead
   = note: this warning originates in the macro `rustler::resource` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unused return value of `Result::<T, E>::is_ok` that must be used
  --> src/lib.rs:49:5
   |
49 |     rustler::resource!(PullSubscriberRef, env);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: if you intended to assert that this is ok, consider `.unwrap()` instead
   = note: this warning originates in the macro `rustler::resource` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unused return value of `Result::<T, E>::is_ok` that must be used
  --> src/lib.rs:50:5
   |
50 |     rustler::resource!(QueryableRef, env);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: if you intended to assert that this is ok, consider `.unwrap()` instead
   = note: this warning originates in the macro `rustler::resource` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unused return value of `Result::<T, E>::is_ok` that must be used
  --> src/lib.rs:51:5
   |
51 |     rustler::resource!(ReplyReceiverRef, env);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: if you intended to assert that this is ok, consider `.unwrap()` instead
   = note: this warning originates in the macro `rustler::resource` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unused return value of `Result::<T, E>::is_ok` that must be used
  --> src/lib.rs:52:5
   |
52 |     rustler::resource!(QueryRef, env);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: if you intended to assert that this is ok, consider `.unwrap()` instead
   = note: this warning originates in the macro `rustler::resource` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unused return value of `Result::<T, E>::is_ok` that must be used
  --> src/lib.rs:53:5
   |
53 |     rustler::resource!(SampleRef, env);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: if you intended to assert that this is ok, consider `.unwrap()` instead
   = note: this warning originates in the macro `rustler::resource` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: `zenohex_nif` (lib) generated 9 warnings
    Finished `release` profile [optimized] target(s) in 3m 37s
Generated zenohex app

```

**Comment by takasehideki** [comment]
I guess the resource registration method may be changed, but cannot find how to upgrade,,,
https://docs.rs/rustler/0.34.0/rustler/macro.resource.html

**Comment by takasehideki** [comment]
With the help of the following various information, I have made modifications to 1b87285. 
https://docs.rs/rustler/0.34.0/rustler/macro.resource.html
https://github.com/rusterlium/rustler/compare/rustler-0.33.0...rustler-0.34.0#diff-77f824b36e0d96ba4f3fee0e86ff2edf9981f4c7df85c91ca8565683e2b2ba40
https://github.com/rusterlium/rustler/blob/master/rustler_tests/native/rustler_test/src/test_resource.rs

As a result, I succeeded in removing the compile-time warning message in Rustler 0.34.0.
However, I'm not at all confident that this modification is correct. Also, there exist the following discussion point:

---
I initially thought [L55 in lib.rs](https://github.com/biyooon-ex/zenohex/pull/69/files#diff-e896709297e1f44aa1ee6957fbd9d37a18e5a66bae046f9960bb607201e3899cR55) should be written as follows.

```
    env.register::<SessionRef>().is_ok();
```

However, another warning message appeared.

```
warning: unused return value of `Result::<T, E>::is_ok` that must be used
  --> src/lib.rs:55:5
   |
55 |     env.register::<SessionRef>().is_ok();
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: if you intended to assert that this is ok, consider `.unwrap()` instead
   = note: `#[warn(unused_must_use)]` on by default
help: use `let _ = ...` to ignore the resulting value
   |
55 |     let _ = env.register::<SessionRef>().is_ok();
   |     +++++++
```

By following this, I decided to write using `unwrap()`. Is it correct??

**Comment by takasehideki** [comment]
@s-hosoai @pojiro If you have time, could you give me advice and/or your knowledge??

**Comment by pojiro** [comment]
@takasehideki 

> I initially thought [L55 in lib.rs](https://github.com/biyooon-ex/zenohex/pull/69/files#diff-e896709297e1f44aa1ee6957fbd9d37a18e5a66bae046f9960bb607201e3899cR55) should be written as follows.

You are right. You need to use them like followings,

```rust
fn load(env: Env, _term: Term) -> bool {
    env.register::<SessionRef>().is_ok()
        && env.register::<PublisherRef>().is_ok()
        && env.register::<SubscriberRef>().is_ok()
        && env.register::<PullSubscriberRef>().is_ok()
        && env.register::<QueryableRef>().is_ok()
        && env.register::<ReplyReceiverRef>().is_ok()
        && env.register::<QueryRef>().is_ok()
        && env.register::<SampleRef>().is_ok()
}
```

`is_ok()` returns boolean, it means `register` works fine. 

ref. https://github.com/rusterlium/rustler/blob/rustler-0.35.0/rustler/src/resource/registration.rs#L129-L155

**Comment by takasehideki** [comment]
About NIF version, we concluded that using 2.15 is reasonable because this is the default version for Rustler we don't have aggressive reasons to use newer features of NIF and OTP. 
To make a note about this, I added [5c0e197](https://github.com/biyooon-ex/zenohex/pull/69/commits/5c0e19781886193d205b07da9306f55f179d6f4b) and made #71.

**Comment by takasehideki** [comment]
@pojiro Thank you so much for your awesome comment!!
I modified code according to your suggestion.
[23eb6aa](https://github.com/biyooon-ex/zenohex/pull/69/commits/23eb6aab52740fed3024238151f986ea86be4e13)

**Comment by takasehideki** [comment]
I'd like to conclude that bumping Rustler to 0.35.0 is not cost-effective and difficult at this time, and that a response to 0.34.0 is sufficient for this PR (now).

Bumping Rustler to 0.35.0 caused many inexplicable compile errors. I guess that these are probably due to that the transition from async-std to Tokio was not yet complete in Zenoh 0.11.0. I have experimentally tried Zenoh 1.0.0 along with Rustler 0.35.0; most of the errors seemed not appear at that time (although many other compile errors happened, so we will have to work on resolving them).

IOW, please review @s-hosoai if this PR is acceptable or not 🙏 
If you agree on this, I will merge it and release Zenohex 0.3.1.

**Review by s-hosoai — CHANGES_REQUESTED** [review]
@takasehideki Thank you for the PR. The modifications you made are fine. 
Additionally, please update the Rustler version in mix.exs. If this PR is upgrading to v0.3.1, please adjust the version accordingly.

**Comment by takasehideki** [comment]
@s-hosoai sorry I can’t catch up what you want me to do,,,

Rustler in mix.lock has already bumped to 0.3.5 by dependabot. You mean this should adjust to 0.3.4? I agree with your this suggestion and will treat it.
https://github.com/biyooon-ex/zenohex/blob/c3f45e7aebeb65a0f323e076fe50d4aa6eaf078e/mix.lock#L23
https://github.com/biyooon-ex/zenohex/pull/61

Or you mean Zenohex should bump to 0.3.1 in this PR too? I don’t think so, The bump to this library should be treated in the separate PR like the below.
https://github.com/biyooon-ex/zenohex/pull/52

**Comment by takasehideki** [comment]
> Rustler in mix.lock has already bumped to 0.3.5 by dependabot. You mean this should adjust to 0.3.4? I agree with your this suggestion and will treat it.

I got it in [e288e6c](https://github.com/biyooon-ex/zenohex/pull/69/commits/e288e6ce2a74c6a94ec8eea2ea75ba90fe50db51).

@s-hosoai could you review again??

**Review by s-hosoai — APPROVED** [review]
The intention was to lock the version to 0.34. Your fix is perfect!
I also agree with handling the Zenohex version upgrade in a separate PR.

**Comment by takasehideki** [comment]
go merging! I will create another PR to release Zenohex 0.3.1.

**Pull request merged**
